targets:
  $default:
    builders:
      json_serializable:
        options:
          create_to_json: true
          include_if_null: false
      drift_dev:
        options:
          databases:
            archive: lib/data/source/database/database.dart
          sql:
            dialect: sqlite
            options:
              modules:
                - json1
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          scoped_dart_components: true